
--// File Generated By Fox-Warrior's Resources Generator Version 2.05 \\--

if (SERVER) then
	resource.AddFile( "sound/bobble/grapple_hook/grappling_hook_impact.mp3" )
	resource.AddFile( "sound/bobble/grapple_hook/grappling_hook_reel_start.wav" )
	resource.AddFile( "sound/bobble/grapple_hook/grappling_hook_reel_stop.mp3" )
	resource.AddFile( "sound/bobble/grapple_hook/grappling_hook_shoot.mp3" )
	
	resource.AddFile( "sound/assassins/hiding.wav" )
	resource.AddFile( "sound/assassins/losing_target.wav" )
	
	resource.AddFile( "sound/assassins/music/ambientloop.wav" )
	resource.AddFile( "sound/assassins/music/guitarloop.wav" )
	resource.AddFile( "sound/assassins/music/postsound.mp3" )
	resource.AddFile( "sound/assassins/music/prepsound.mp3" )
	resource.AddFile( "sound/assassins/music/suspenseloop.wav" )
	resource.AddFile( "sound/assassins/music/suspensetoguitar.wav" )
	
	resource.AddFile( "models/player/assassins/animationbase.mdl" )
	
	resource.AddFile( "materials/assassins/smallcircleload.vmt" )
	resource.AddFile( "materials/assassins/smallcircleload.vtf" )
	resource.AddFile( "materials/assassins/smallcircleload_col.vmt" )
	resource.AddFile( "materials/assassins/smallcircleload_col.vtf" )
	
	resource.AddFile( "materials/assassins/tut/tut1.png" )
	resource.AddFile( "materials/assassins/tut/tut2.png" )
	resource.AddFile( "materials/assassins/tut/tut3.png" )
	resource.AddFile( "materials/assassins/tut/tut4.png" )
	resource.AddFile( "materials/assassins/tut/tut5.png" )
	resource.AddFile( "materials/assassins/tut/tut6.png" )
	resource.AddFile( "materials/assassins/tut/tut7.png" )
	resource.AddFile( "materials/assassins/tut/tut8.png" )
end